// MOVIE ACTION TYPES

export const FETCH_TRENDING_MOVIE_START = 'FETCH_TRENDING_MOVIE_START'
export const FETCH_TRENDING_MOVIE_SUCCESS = 'FETCH_TRENDING_MOVIE_SUCCESS'
export const FETCH_TRENDING_MOVIE_FAIL = 'FETCH_TRENDING_MOVIE_FAIL'

export const FETCH_THEATRE_MOVIE_START = 'FETCH_THEATRE_MOVIE_START'
export const FETCH_THEATRE_MOVIE_SUCCESS = 'FETCH_THEATRE_MOVIE_SUCCESS'
export const FETCH_THEATRE_MOVIE_FAIL = 'FETCH_THEATRE_MOVIE_FAIL'


export const FETCH_HIGHESTRATED_MOVIE_START = 'FETCH_HIGHESTRATED_MOVIE_START'
export const FETCH_HIGHESTRATED_MOVIE_SUCCESS = 'FETCH_HIGHESTRATED_MOVIE_SUCCESS'
export const FETCH_HIGHESTRATED_MOVIE_FAIL = 'FETCH_HIGHESTRATED_MOVIE_FAIL'

export const FETCH_UPCOMMING_MOVIE_START = 'FETCH_UPCOMMING_MOVIE_START'
export const FETCH_UPCOMMING_MOVIE_SUCCESS = 'FETCH_UPCOMMING_MOVIE_SUCCESS'
export const FETCH_UPCOMMING_MOVIE_FAIL = 'FETCH_UPCOMMING_MOVIE_FAIL'

export const FETCH_POPULAR_MOVIE_START = 'FETCH_POPULAR_MOVIE_START'
export const FETCH_POPULAR_MOVIE_SUCCESS = 'FETCH_POPULAR_MOVIE_SUCCESS'
export const FETCH_POPULAR_MOVIE_FAIL = 'FETCH_POPULAR_MOVIE_FAIL'

// TV ACTION TYPES

export const FETCH_TRENDING_TV_START = 'FETCH_TRENDING_TV_START'
export const FETCH_TRENDING_TV_SUCCESS = 'FETCH_TRENDING_TV_SUCCESS'
export const FETCH_TRENDING_TV_FAIL = 'FETCH_TRENDING_TV_FAIL'

export const FETCH_HIGHESTRATED_TV_START = 'FETCH_HIGHESTRATED_TV_START'
export const FETCH_HIGHESTRATED_TV_SUCCESS = 'FETCH_HIGHESTRATED_TV_SUCCESS'
export const FETCH_HIGHESTRATED_TV_FAIL = 'FETCH_HIGHESTRATED_TV_FAIL'

export const FETCH_POPULAR_TV_START = 'FETCH_POPULAR_TV_START'
export const FETCH_POPULAR_TV_SUCCESS = 'FETCH_POPULAR_TV_SUCCESS'
export const FETCH_POPULAR_TV_FAIL = 'FETCH_POPULAR_TV_FAIL'

export const FETCH_AIRINGTODAY_TV_START = 'FETCH_AIRINGTODAY_TV_START'
export const FETCH_AIRINGTODAY_TV_SUCCESS = 'FETCH_AIRINGTODAY_TV_SUCCESS'
export const FETCH_AIRINGTODAY_TV_FAIL = 'FETCH_AIRINGTODAY_TV_FAIL'

export const FETCH_ONAIR_TV_START = 'FETCH_ONAIR_TV_START'
export const FETCH_ONAIR_TV_SUCCESS = 'FETCH_ONAIR_TV_SUCCESS'
export const FETCH_ONAIR_TV_FAIL = 'FETCH_ONAIR_TV_FAIL'

// Type selector action types
export const CHANGE_TO_MOVIES = 'CHANGE_TO_MOVIES'
export const CHANGE_TO_TV = 'CHANGE_TO_TV'

// more info fetch requests
export const FETCH_MOREINFO_START = 'FETCH_MOREINFO_START'
export const FETCH_MOREINFO_SUCCESS = 'FETCH_MOREINFO_SUCCESS'
export const FETCH_MOREINFO_FAIL = 'FETCH_MOREINFO_FAIL'

export const FETCH_GETREVIEWS_START = 'FETCH_GETREVIEWS_START'
export const FETCH_GETREVIEWS_SUCCESS = 'FETCH_GETREVIEWS_SUCCESS'
export const FETCH_GETREVIEWS_FAIL = 'FETCH_GETREVIEWS_FAIL'

export const FETCH_SIMILAR_START = 'FETCH_SIMILAR_START'
export const FETCH_SIMILAR_SUCCESS = 'FETCH_SIMILAR_SUCCESS'
export const FETCH_SIMILAR_FAIL = 'FETCH_SIMILAR_FAIL'

export const FETCH_TRAILER_START = 'FETCH_TRAILER_START'
export const FETCH_TRAILER_SUCCESS = 'FETCH_TRAILER_SUCCESS'
export const FETCH_TRAILER_FAIL = 'FETCH_TRAILER_FAIL'

// search action types
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'

// Discover action types
export const FETCH_DISCOVER_START = 'FETCH_DISCOVER_START'
export const FETCH_DISCOVER_SUCCESS = 'FETCH_DISCOVER_SUCCESS'
export const FETCH_DISCOVER_FAIL = 'FETCH_DISCOVER_FAIL'

// auth action types
export const FETCH_REQUESTTOKEN_START = 'FETCH_REQUESTTOKEN_START';
export const FETCH_REQUESTTOKEN_SUCCESS = 'FETCH_REQUESTTOKEN_SUCCESS';
export const FETCH_REQUESTTOKEN_FAIL = 'FETCH_REQUESTTOKEN_FAIL';


export const FETCH_GET_SESSION_ID_START = 'FETCH_GET_SESSION_ID_START';
export const FETCH_GET_SESSION_ID_SUCCESS = 'FETCH_GET_SESSION_ID_SUCCESS';
export const FETCH_GET_SESSION_ID_FAIL = 'FETCH_GET_SESSION_ID_FAIL';

export const CHANGE_LOGIN_STATUS = 'CHANGE_LOGIN_STATUS';
export const LOG_OUT = 'LOG_OUT';

// account lists action types
export const CHANGE_LIST_TYPE = 'CHANGE_LIST_TYPE';