export const FETCH_TRENDING_MOVIE_START = 'FETCH_TRENDING_MOVIE_START'
export const FETCH_TRENDING_MOVIE_SUCCESS = 'FETCH_TRENDING_MOVIE_SUCCESS'
export const FETCH_TRENDING_MOVIE_FAIL = 'FETCH_TRENDING_MOVIE_FAIL'
