export const FETCH_TRENDING_MOVIE_START = 'FETCH_TRENDING_MOVIE_START'
export const FETCH_TRENDING_MOVIE_SUCCESS = 'FETCH_TRENDING_MOVIE_SUCCESS'
export const FETCH_TRENDING_MOVIE_FAIL = 'FETCH_TRENDING_MOVIE_FAIL'

export const FETCH_THEATRE_MOVIE_START = 'FETCH_THEATRE_MOVIE_START'
export const FETCH_THEATRE_MOVIE_SUCCESS = 'FETCH_THEATRE_MOVIE_SUCCESS'
export const FETCH_THEATRE_MOVIE_FAIL = 'FETCH_THEATRE_MOVIE_FAIL'


export const FETCH_HIGHESTRATED_MOVIE_START = 'FETCH_HIGHESTRATED_MOVIE_START'
export const FETCH_HIGHESTRATED_MOVIE_SUCCESS = 'FETCH_HIGHESTRATED_MOVIE_SUCCESS'
export const FETCH_HIGHESTRATED_MOVIE_FAIL = 'FETCH_HIGHESTRATED_MOVIE_FAIL'

export const FETCH_UPCOMMING_MOVIE_START = 'FETCH_UPCOMMING_MOVIE_START'
export const FETCH_UPCOMMING_MOVIE_SUCCESS = 'FETCH_UPCOMMING_MOVIE_SUCCESS'
export const FETCH_UPCOMMING_MOVIE_FAIL = 'FETCH_UPCOMMING_MOVIE_FAIL'

export const FETCH_POPULAR_MOVIE_START = 'FETCH_POPULAR_MOVIE_START'
export const FETCH_POPULAR_MOVIE_SUCCESS = 'FETCH_POPULAR_MOVIE_SUCCESS'
export const FETCH_POPULAR_MOVIE_FAIL = 'FETCH_POPULAR_MOVIE_FAIL'